# config/sidekiq.yml
:concurrency: 5

:queues:
  - default

:schedule:
  generate_montly_report:
    cron: '0 2 1 * *'  # each 1 day of month at 2:00 AM
    class: GenerateMonthlyTransactionsReportJob
    queue: default
    description: Generates a monthly report of transactions and clean the DB